### ISSUE TITLE
Inkscape 1.0 plots at wrong scale due to deprecates functions: simpletransform etc.

### ISSUE THREAD

**Issue by t0b3** [fablabnbg/inkscape-silhouette#101]
> Your wish let me work...but keep in mind: the extension is exactly the same, both Version use the SAME!! HOME partition.
> 
> Ubuntu Stdio 19.10 with inkscape 0.92.5 produces a nice output:
[silhouette.dump.zip](https://github.com/fablabnbg/inkscape-silhouette/files/4639163/silhouette.dump.zip)
> 
> On Ubuntu 20.04 / inkscape 1.0 python wont be found this way..
![Bildschirmfoto von 2020-05-16 22-26-16](https://user-images.githubusercontent.com/17491743/82129604-585b8b00-97c4-11ea-9c91-50a57a9868fd.png)
> 
> Called explicitly with python3 did run but output is different...
[terminal-output-20.04.zip](https://github.com/fablabnbg/inkscape-silhouette/files/4639202/terminal-output-20.04.zip)
> 
> and the dump
> [silhouette.dump-20.04.zip](https://github.com/fablabnbg/inkscape-silhouette/files/4639191/silhouette.dump-20.04.zip)

_Originally posted by @bianchifan in https://github.com/fablabnbg/inkscape-silhouette/issues/90#issuecomment-629704114_

@bianchifan I had a look at your dump files. they tell us quite a lot. the numer of points differ by 
* number of points
* scale
* placement of the letter 'o'

to evaluate dump files you may use [read_dump.py](https://github.com/fablabnbg/inkscape-silhouette/files/4639396/read_dump.py.txt)
![image](https://user-images.githubusercontent.com/5751047/82131437-754c8a00-97d5-11ea-8fc0-db72820234db.png)
this explains your issue. nb: the dump reproduces here. 
it looks like an error processing svg transform attribute with new inkex.

**Comment by bianchifan** [comment]
OK..just two thoughts:
1st, unequal dump files due to different implementation and versions of python
2nd, your plots are nice but the output on my Cameo 2 rides other routes

Current (not really) working system: Ubuntu 20.04, upgraded from 19.10, roundabout 500 pragrams were purged during upgrade:((
python -> not installed, when trying to reinstall -> deprecated
python2 -> python 2.7
python3 -> python 3.8
Every call of "python" results in "not found", you must explicitly call python2 or python3.
When calling python3, python 3.8**!** is used.

Ubuntu Studio 10.10:
python -> python 2.7
python2 -> python 2.7
python3 -> python 3.7
When you call python, python 2.7 is used, in case of python3 python 3.7**!**

To the plots:
My pyplots differ to yours due to python 3.8
dump_19.10
![Figure_19 10](https://user-images.githubusercontent.com/17491743/82139029-5fff4c00-9825-11ea-9c75-3178007e20bc.png)
dump_20.04
![Figure_20 04](https://user-images.githubusercontent.com/17491743/82139031-61c90f80-9825-11ea-94f1-1db778ece154.png)
But the plotter took different routes again..

19.10
Logo, C, 1st o, l, H, Logo, 2nd o, 3rd o (maybe Logo again, I'm not shure)

20.04
all objects are cut, truncated
Logo, C, 1st o, l, H, 2nd o, 3rd o
The "H" for ex. consists of 4! lines

The sendto-script isn't all, there should happen many weird stuff later on

**Comment by t0b3** [comment]
Well it's not about python versions, because Inkscape 0.95.2 wich works with both py2 and py3 works nice with your svg. However Inkscape 1.0 providing different inkex.py requires some adaptations in the inkscape-silhouette code to make such svg work again...

Just for information:
The relevant part of your terminal output is
```
./sendto_silhouette.py:991: DeprecationWarning: simpletransform.parseTransform -> Transform(str).matrix
  self.docTransform = parseTransform( 'scale(%f,%f)' % (sx, sy) )
./sendto_silhouette.py:517: DeprecationWarning: simpletransform.composeParents -> elem.composed_transform() or elem.transform * Transform(mat)
  transform = composeParents(node, IDENTITY_TRANSFORM)
./sendto_silhouette.py:518: DeprecationWarning: simpletransform.composeTransform -> Transform(M1) * Transform(M2)
  transform = composeTransform(self.docTransform, transform)
./sendto_silhouette.py:519: DeprecationWarning: simpletransform.composeTransform -> Transform(M1) * Transform(M2)
  transform = composeTransform(extra_transform, transform)
./sendto_silhouette.py:406: DeprecationWarning: simplepath.parsePath -> element.path.to_arrays()
  if len( simplepath.parsePath( d ) ) == 0:
./sendto_silhouette.py:409: DeprecationWarning: cubicsuperpath.parsePath -> None
  p = cubicsuperpath.parsePath( d )
./sendto_silhouette.py:412: DeprecationWarning: simpletransform.applyTransformToPath -> Path(path).transform(mat)
  applyTransformToPath( matTransform, p )
./sendto_silhouette.py:215: DeprecationWarning: inkex.bezier.maxdist -> Get maximum distance within bezier curve
  if cspsubdiv.maxdist( b ) > flat:
./sendto_silhouette.py:220: DeprecationWarning: inkex.bezier.beziersplitatt -> Split bezier at given time
  one, two = beziersplitatt( b, 0.5 )
```

It is because those functions to process the `transform` attribute in your svg (lines 30,73,86) don't work with Inkscape 1.0 because it introduces some breaking changes to API in [inkscape extensions](https://gitlab.com/inkscape/extensions).

inkscape-silhouette.py code needs to reimplement the processing of path transformation [i.e. at lines 516ff](https://github.com/fablabnbg/inkscape-silhouette/blob/master/sendto_silhouette.py#L516-L519)

contributions are most welcome...

**Comment by jnweiger** [comment]
This is the oldest code that I have done. Most newer projects use my inksvg module to handle the path transforms. But I am fraud, reading the above, that my inksvg would face the same issues. :-(
I wanted to look into this for months, but failed to find the time. Sigh. The api changes should not break. We have many deprecations, but afaik, there was no intention to break.

@t0b3 Thanks for your numerous and quality contributions here!

**Comment by uxwalter** [comment]
FWIW, I changed inkscape-silhouette to get rid of all warnings that come with inkscape version 1.0. I also had the scaling issue. It seems that version 1.0 uses mm as the default unit instead of px when sending data to extensions so the hardcoded scaling in sendto_silhouette.py's px2mm is no longer applicable. Changing the return to simply "return px" fixed my scaling issues. I don't know if this is a default change across the board for 1.0 or something with my (i.e. Fedora's) setup/distro. This is not something to work around with settings in inkscape itself.

**Comment by bianchifan** [comment]
THX for your help but for me the result is even worse..
It exceeds the boundings of my plotter: ~ 11(18)cm x 60cm instead of ~ 3cm X 16cm ;)
![Figure_1](https://user-images.githubusercontent.com/17491743/86510968-e29f9300-bdf4-11ea-81f9-1dc2ed85d558.png)
![Bildschirmfoto von 2020-07-04 12-18-57](https://user-images.githubusercontent.com/17491743/86511014-707b7e00-bdf5-11ea-851d-cf8f16e26374.png)

**Comment by uxwalter** [comment]
Two things.
1. Take the first deprecation message. It's because s.read in line 433 uses the read function defined in line 391. Which in turn uses .tostring() on line 412 (and only there). The PR changes line 412 to tobytes(). Hence that warning should no longer be there. Check line 412 in  /home/majo/.config/inkscape/extensions/silhouette/Graphtec.py. If it says tostring() then it's not the version from this PR. If it is then I have no idea what's going on.

2. Fixing #1 is unlikely to fix the scaling issue but stranger things have happened. Let's try this:
- Unzip [debug_silhouette.zip](https://github.com/fablabnbg/inkscape-silhouette/files/4873791/debug_silhouette.zip). Open the .sh file and adjust paths to match your environment. I.e., change the first and last line only.
- Run debug_silhouette.sh
- It should have created silhouette.dump, most likely in /tmp. Compare it to the one that's included in the .zip file. If they're the same then the scaling problem is solved and it's likely something in your inkscape settings or still something odd in your extension files. If they are different then add the file here and I'll take a look to see if there's anything obvious.

**Comment by bianchifan** [comment]
>     1. Take the first deprecation message.
deprecation messages are gone due to new Graphtec.py :)

>     2. Fixing #1 is unlikely to fix the scaling issue but stranger things have happened. Let's try this:
...
>  If they're the same then the scaling problem is solved and it's likely something in your inkscape settings or still something odd 
>  in your extension files.

The dumps are equal.
But scalings with my "CooloH.svg" are still odd.
Dumping produces some more output now:
[terminal_output.txt](https://github.com/fablabnbg/inkscape-silhouette/files/4874869/terminal_output.txt)

**Comment by uxwalter** [comment]
So there's still something off in the handoff from inkscape to the plugin if the simple box produces the correct output at the correct scale. If you attach the .svg file that's still plotted incorrectly here I'd be happy to take a look.

**Comment by t0b3** [comment]
@uxwalter you may find the mentioned svg here https://github.com/fablabnbg/inkscape-silhouette/issues/90#issuecomment-629666124

**Comment by EtherGraf** [comment]
@t0b3 Is it ok for you, if I add the read_dump.py tool to the sourcecode?

**Comment by t0b3** [comment]
@EtherGraf You may add read_dump.py to the source code under the GPL2
License.

Another question:
Are you ready to merge PR 99 and automate testing of code contributions for
py2 and py3 on Mac, win and Linux?
https://github.com/fablabnbg/inkscape-silhouette/pull/99
In case my explanation on the purpose was too short to be understandable I
will provide in depth explanation...

**Comment by t0b3** [comment]
@bianchifan you are welcome to retry with the latest code in master and provide feedback or open new issues. 
It works with Inkscape 1.0 as well. See https://travis-ci.com/github/fablabnbg/inkscape-silhouette for more details.
NB: your provided example should work fine now.
