### ISSUE TITLE
Extension fails if units set to inches

### ISSUE THREAD

**Issue by hellocatfood** [fablabnbg/inkscape-silhouette#19]
I changed the units in an inkscape document from millimetres to inches. When I send a docuemnt to the machine the plugin fails and returns the following error

Traceback (most recent call last):
  File "sendto_silhouette.py", line 1042, in <module>
    e.affect()
  File "/usr/share/inkscape/extensions/inkex.py", line 271, in affect
    self.effect()
  File "sendto_silhouette.py", line 990, in effect
    mediawidth=px2mm(self.docWidth),
  File "sendto_silhouette.py", line 119, in px2mm
    return px*25.4/90
TypeError: unsupported operand type(s) for *: 'NoneType' and 'float'

When I change it back to millimetres it works. I think either this should be fixed of specified in the README that it only works with millimetres

**Comment by jnweiger** [comment]
Ah, I haven't tried that. I usually work with px or mm. Both work fine for me. Strange that inches behave differently.

**Comment by jnweiger** [comment]
Fixed in version 1.18 -- the recycled eggbot-code did not support inches. Added that.
We still miss support for units pc and pt, if someone knows the exact formula for this, please feel free to enhance the GetLengh function near https://github.com/fablabnbg/inkscape-silhouette/blob/cdac06d121c22c4d3854a3e62dac224c3293e5b8/sendto_silhouette.py#L859
