### ISSUE TITLE
Media settings

### ISSUE THREAD

**Issue by mase76** [fablabnbg/inkscape-silhouette#5]
Hi!
Where can I find a reference for the MediaId?
How do I know, what Id, pressure and speed I have to set up.
How to set up the blade? The extension should tell me all that.

**Comment by jnweiger** [comment]
The media table is at the beginning of silhouette/Graphtec.py -- I have no idea, how to put it in sendto_silhouette.inx so that it is accessible in the gui. Suggestions welcome.

MEDIA = [

# media, pressure, speed, cap-color, name

  ( 100,   27,     10,  "yellow", "Card without Craft Paper Backing"),
  ( 101,   27,     10,  "yellow", "Card with Craft Paper Backing"),
  ( 102,   10,     10,  "blue",   "Vinyl Sticker"),
  ( 106,   14,     10,  "blue",   "Film Labels"),
  ( 111,   27,     10,  "yellow", "Thick Media"),
  ( 112,    2,     10,  "blue",   "Thin Media"),
  ( 113,   10,     10,  "pen",    "Pen"),
  ( 120,   30,     10,  "blue",   "Bond Paper 13-28 lbs (105g)"),
  ( 121,   30,     10,  "yellow", "Bristol Paper 57-67 lbs (145g)"),
  ( 122,   30,     10,  "yellow", "Cardstock 40-60 lbs (90g)"),
  ( 123,   30,     10,  "yellow", "Cover 40-60 lbs (170g)"),
  ( 124,    1,     10,  "blue",   "Film, Double Matte Translucent"),
  ( 125,    1,     10,  "blue",   "Film, Vinyl With Adhesive Back"),
  ( 126,    1,     10,  "blue",   "Film, Window With Kling Adhesive"),
  ( 127,   30,     10,  "red",    "Index 90 lbs (165g)"),
  ( 128,   20,     10,  "yellow", "Inkjet Photo Paper 28-44 lbs (70g)"),
  ( 129,   27,     10,  "red",    "Inkjet Photo Paper 45-75 lbs (110g)"),
  ( 130,   30,      3,  "red",    "Magnetic Sheet"),
  ( 131,   30,     10,  "blue",   "Offset 24-60 lbs (90g)"),
  ( 132,    5,     10,  "blue",   "Print Paper Light Weight"),
  ( 133,   25,     10,  "yellow", "Print Paper Medium Weight"),
  ( 134,   20,     10,  "blue",   "Sticker Sheet"),
  ( 135,   20,     10,  "red",    "Tag 100 lbs (275g)"),
  ( 136,   30,     10,  "blue",   "Text Paper 24-70 lbs (105g)"),
  ( 137,   30,     10,  "yellow", "Vellum Bristol 57-67 lbs (145g)"),
  ( 138,   30,     10,  "blue",   "Writing Paper 24-70 lbs (105g)"),
  ( 300, None,   None,  "custom", "Custom"),
]

**Comment by iromero91** [comment]
Hello, i replaced the number field with a dropdown list, made a pull request (#9) with the proposed change.

**Comment by dy-wen** [comment]
Hey

Great software! 
Wow.. 
A few questions. --> Related to the media size and in general.
---> What do you exactly compile?  --> what's in the deb --> communication with the Silhouette Cameo?
--> do you have specs on size?
I made a test paper - it seems to be pretty much the inner square of the cutting mat. 30cm on 30cm
--> in the long run, would it be possible to cut very long stickers?
In theory the Silhouette Cameo is capable to do this. 

We will cut some ironable circuits on copper fabric in a workshop in Senegal very very soon!

Anyway, keep up the good work!

Greetings from Brussels,
Wendy

**Comment by jnweiger** [comment]
The entries in the dropdown menu now expose their P and S settings, so that users can choose variations.

**Comment by jnweiger** [comment]
@dy-wen Hey Wendy, did the copper fabric circuit cutting work? I'd be interested to know more about this!
Yes, you can cut stickers (or banners) up to 3m long.

**Comment by jnweiger** [comment]
@mase76 There are no well known values for the blade setting. This also depends how sharp the blade is, and how strong the cutting mat is. I often go with 2 or 3 with both thermo-transfer foils and adhesive sticker foils. Experiments will tell you.

**Comment by probonopd** [comment]
> Yes, you can cut stickers (or banners) up to 3m long.

That's great to know, does this apply for all models including the ("A4") silhouette portrait?

**Comment by dy-wen** [comment]
Hey,

The Copper fabric cutting actually goes really well.
- I used fabric from:
  http://www.lessemf.com/fabric4.html#1212
  The problem is more that this type of fabric is not so easy to get in Europe..
  I cut it on a cutting mat, in combination with ironable glue on the other side (so you iron your circuit on fabric)
  You can also solder on the copper fabric, but it is very fragile. 
  When I get round to having pictures (I won't have access to my material for a few months - abroad), I'll update this post!
- You can also cut copper tape: http://www.kobakant.at/DIY/?p=5371

Greetz & thanks,

dy-wen

**Comment by jnweiger** [comment]
@dy-wen Great links! thanks for the info!

**Comment by jnweiger** [comment]
@probonopd sorry, I only know for the Cameo for sure, I'd assume they have the same controller. But you can just try, draw a 3m high rectangle in inkscape, remove the blade from your portrait and watch it spooling forward backward.
