### ISSUE TITLE
Wrong position after job has finished

### ISSUE THREAD

**Issue by mase76** [fablabnbg/inkscape-silhouette#6]
Hi!
When a job was finished, the device seems not to go to its correct position.
When redoing the same job, I have a significant offset. So it is not possible
to cut a job twice.
Reloading would also end up in an offset.

**Comment by jnweiger** [comment]
On my machine, the position after a cut is exactly as before the cut. 

Please try to find a very simple pattern, that demonstrates the offset.
 -> attach the svg file, so that I can check, if it is the same on my machine or not.

Can you try to capture the log? If you are on linux:
 open a text console. Run the command "script" 
run "inkscape" and cut the most simple example, that reporduces the offset.
exit inkscape, type "exit" to the shell, the file 'typescript' should now contain the log.

Can you tell if the offset is more with a more complex pattern, or with a larger pattern, ... ?

Can you check the firmware version of you Silhouette Cameo? Maybe it is much newer or much older than mine?

thanks for reporting!

**Comment by mase76** [comment]
Another try with a more simple pattern worked as it should.
I am on Debian Jessie.
Now I have a problem, that the cut is 10mm too much to the right and 5mm
too much on top. I am trying to figure out, if the problem persists...
Where can I see the FW version? Can it be updated?

**Comment by mase76** [comment]
Yes, the same with an other project. 10mm too much to the right and
5mm too much on top.

**Comment by jnweiger** [comment]
The borders are wrong. That is a known issue. You can compensate for that with negative x-offset and y-offset.

Re Firmware version: when starting, one of the messages that are printed to the terminal is:
 device version: XXXXXXX

You say, that a more simple pattern works as it should. Can you send me both, the pattern that fails, and the one that works? Maybe I can spot the difference.

**Comment by mase76** [comment]
I took this pattern:
http://openclipart.org/detail/194596/little-house-cutout-by-ulrike-194596
I made it fit to A4.
Then I let draw all the lines with the pen to get the folding edges.
Then I removed all the folding edges to cut out the pattern.
I expected, that the cutting and the drawing must match, but it did not.
See the pattern, then you will see what I mean.

When I set an offset of -10mm, there is an 10mm area, that is not cut.

**Comment by jnweiger** [comment]
I'll download and test http://openclipart.org/download/people/Ulrike/little-boxes-1.svg
when I can access my Cameo later this week.

I noticed the non-cuttable 10mm before, but forgot about it. Thanks for bringing it up again.

**Comment by mase76** [comment]
I measured out the offsets:
x = -12mm
y = -6mm
But the machine does not handle this. Seems to be the problem with the uncutable area.
As a workaround I move the paper on the cutting map 12mm to the left and 6mm to the
bottom.

**Comment by jnweiger** [comment]
Regarding your initial comment: I noticed that the blue lever can hit the white roller, when moving leftward.
When this happens, a mechanical horizontal offset is introduced. Only a power-cycle would currently help.

**Comment by jnweiger** [comment]
Up to including version 1.9d the 'Trim Margin' checkmark is broken. 
It moves the design to the top lefthand corner without respecting the hardware margin.

**Comment by jnweiger** [comment]
fixed in version 1.10
